# Generated by Django 5.2.17 on 2026-10-01 07:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import rentsolutions.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', rentsolutions.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('amenities', models.TextField(blank=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rentsolutions.landlord')),
            ],
            options={
                'verbose_name_plural': 'rental properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RentalPropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_number', models.CharField(max_length=50)),
                ('management_start_date', models.DateField()),
                ('management_end_date', models.DateField(blank=True, help_text='Access stops on this date.', null=True)),
                ('property_managed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='rentsolutions.rentalproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-management_start_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_identity', models.CharField(max_length=50, verbose_name='unit')),
                ('unit_notes', models.TextField(blank=True, verbose_name='notes')),
                ('property_with_rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rentsolutions.rentalproperty')),
            ],
            options={
                'ordering': ['unit_identity'],
            },
        ),
        migrations.CreateModel(
            name='RentalUnitMonthlyRentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_date', models.DateField(help_text='Rates start on the first of a month; a mid-month date starts next month.')),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_rates', to='rentsolutions.rentalunit')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255, verbose_name='name')),
                ('national_id_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('date_tenancy_starts', models.DateField(verbose_name='tenancy starts')),
                ('date_tenancy_ends', models.DateField(blank=True, null=True, verbose_name='tenancy ends')),
                ('rental_unit_occupied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='rentsolutions.rentalunit', verbose_name='rental unit')),
            ],
            options={
                'ordering': ['-date_tenancy_starts'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_paid', models.DateField()),
                ('intended_payment_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='paying for month')),
                ('intended_payment_year', models.PositiveSmallIntegerField(verbose_name='paying for year')),
                ('payment_details', models.TextField(blank=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('tenant_paying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentsolutions.tenant')),
            ],
            options={
                'ordering': ['-date_paid', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='rentalunit',
            constraint=models.UniqueConstraint(fields=('property_with_rental_unit', 'unit_identity'), name='unique_unit_name_per_property'),
        ),
        migrations.AddConstraint(
            model_name='rentalunitmonthlyrentrate',
            constraint=models.UniqueConstraint(fields=('rental_unit', 'start_date'), name='one_rent_rate_per_unit_per_month'),
        ),
    ]
