# Generated by Django 4.2.9 on 2024-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0002_alter_tenant_rental_unit_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='rental_unit_paid_for',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
