# Generated by Django 4.2.9 on 2024-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0002_rentalunit_occupant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
