# Generated by Django 4.2.9 on 2024-02-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0003_payment_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScreeshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshot_images/')),
                ('rentalUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentsolutions.rentalunit')),
            ],
        ),
    ]
