# Generated by Django 4.2.9 on 2024-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0003_rentpayment_rental_unit_paid_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunitmonthlyrentrate',
            name='rental_unit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
