# Generated by Django 4.2.9 on 2024-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0004_rentalunitmonthlyrentrate_rental_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunitmonthlyrentrate',
            name='rental_unit_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
