# Generated by Django 4.2.9 on 2024-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0005_rentalunitmonthlyrentrate_rental_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunitmonthlyrentrate',
            name='rental_unit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
