# Generated by Django 4.2.9 on 2024-03-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0006_alter_rentalunitmonthlyrentrate_rental_unit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalunitmonthlyrentrate',
            old_name='rental_unit_id',
            new_name='unit_absolute_identity',
        ),
    ]
