# Generated by Django 4.2.9 on 2024-03-30 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0009_rentalpropertymanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalpropertymanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_property_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
