# Generated by Django 4.2.9 on 2024-03-30 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentsolutions', '0010_alter_landlord_user_alter_rentalpropertymanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalpropertymanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_property_managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
